#!/usr/bin/env ruby
require "webrick"
require "json"
require "logger"

class MyServlet < WEBrick::HTTPServlet::AbstractServlet
  RESULT = { title: "test title", userId: 1, version: ENV["VERSION"] || "0" }

  def do_GET(_request, response)
    response.status = 200
    response.content_type = "application/json"
    response.body = RESULT.to_json + "\n"
  end

  def do_POST(_request, response)
    response.status = 201
    response.content_type = "application/json"
    response.body = RESULT.to_json + "\n"
  end

  def do_PUT(_request, response)
    response.status = 200
    response.content_type = "application/json"
    response.body = RESULT.to_json + "\n"
  end

  def do_DELETE(_request, response)
    response.status = 200
    response.content_type = "application/json"
    response.body = RESULT.to_json + "\n"
  end
end

port = ENV.fetch("PORT").to_i
logger = Logger.new(File.open("/dev/null", "a+"))
#logger = Logger.new(File.open("log/test.log", "a+"))
server = WEBrick::HTTPServer.new(Port: port, Logger: logger, AccessLog: logger)
#server = WEBrick::HTTPServer.new(Port: port)

server.mount "/", MyServlet

trap("INT") { server.shutdown }

STDERR.puts "Starting server"

server.start
